#!/bin/bash
# profile information
# Mike Perron (2013)
#
# Creates markup for user/profile information.

drawtool(){
	if [ -z "$kraknet_user" ]; then exit 1; fi
	cat <<-EOF
		<div id=profile_tool>
			<a href=/den/user.html>$kraknet_user</a>
		</div>
	EOF
}
drawlogin(){
	cat <<-EOF
		<div id=profile_tool>
			<form method=post action=accounts/login>
				<input type=hidden name=onsuccess value=/den/>
				<input type=hidden name=onfailure value=/den/?failure>
				<input name=name>
				<input type=password name=pass>
				<input type=submit value=Login>
			</form>
		</div>
	EOF
}

if [ "$kraknet_user_auth" == "OK" ]; then drawtool; else drawlogin; fi
