#!/bin/bash
# Print a cute tagline for the page header.

tags=(
	"Join your friends, sheep."
	"Drugs are bad, mmm'kay?"
	"Definitely not Facebook!"
	"Like MySpace, but cooler."
	"It's definitely \"in beta.\""
	"When it's Done.&trade;"
	"Soon.&trade;"
	"The Future is Now!"
	"The Future is Soon!"
	"The Future is Yesterday!"
	"The Future...is!"
	"Definitely not Krakchat!"
	"Runs on <a href=//github.com/krakissi/kraknet>Kraknet</a>!"
	"No LAMPs in this Krakhouse!"
)

a=$RANDOM
let "a %= ${#tags[@]}"
printf "%s" "${tags[$a]}"
